### ISSUE TITLE
unable to find podspec for RNImageHelper

### ISSUE THREAD

**Issue by apski** [prscX/react-native-image-helper#1]
When I try to do `pod install` I get: 
```
➜ pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `RNImageHelper` depended upon by `RNBottomActionSheet`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

```
When I add `pod 'RNImageHelper',  :git => 'https://github.com/prscX/react-native-image-helper.git'` to my pod file I get the following: 

```
➜ pod install --repo-update
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `RNImageHelper` from `https://github.com/prscX/react-native-image-helper.git`
[!] Unable to find a specification for 'RNImageHelper'.
```

**Comment by prscX** [comment]
@apski: Could you please share the library name you are trying to install? As per shared logs, I believe it is RNBottomSheet?

You need to add below snippet to your Podfile:

```
pod 'RNImageHelper', :path => '../node_modules/react-native-image-helper/ios'
```

Thanks
</ Pranav >

**Comment by batrinuvlad** [comment]
I've had the same problem with RNNotifcationBanner podspec, and adding in podfile fixed it, thank you!
